#+title: Revised Oxford Bioinformatics template

This repository contains a cleaned up template for Oxford Bioinformatics.
The starting point (initial commit) is the version on Overleaf [[https://www.overleaf.com/latex/templates/template-for-oxford-bioinformatics-journal-new-version/zjrmbrmtrytg][here]].
See the git history or remarks below for a list of changes.

** Usage
Clone the repository and run ~make~ from the repository root.

** Changes
- Remove OUP from front page footer, and add copyright symbol for even first pages.
- Remove Bioinformatics and image from front page header, remove ~\access~ and ~\appnotes~.
- Remove crop markers and change physical page size to ~11truein~ by ~8.5truein~.
- Empty ~\subsection{}~, ~\history{}~, and ~\access{}~.
- Remove ~plain.bst~.
- Rename ~document.bib~ to ~bibliography.bib~.
- Move text from ~main.tex~ into ~paper/*.tex~.
- Add appendix.
- Add ~T1~ font encoding to ~fontenc~ package for smallcaps support. NOTE: This changes the size of ~em~.
- Change abstract and top rule to be the full page width.
- Fix slightly off-center page by forcing left and right margins to be equal on
  both even and odd pages.
- Redefine ~\paragraph{title}~ to print the paragraph title in bold, followed by
  a period.
